FROM python:3.9-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN mkdir /app
WORKDIR /app

COPY . .

RUN python3 extract_pdf_paragraphs/download_punkt.py
CMD python3 RedisTasksProcessor.py

