#!/bin/bash

set -eo pipefail

function _source_venv {
  {
    source venv/bin/activate 2>&1
  } || {
    printf '\e[31m\n%s\n\n\e[0m' 'Venv does not exist, create it running ./run install_venv'
    exit 1
  }
}

function install_venv {
  python3 -m venv venv
  source venv/bin/activate
  python3 -m pip install --upgrade pip
  python3 -m pip install -r requirements.txt
  printf '\e[33m\n%s\n\n\e[0m' '"source ./venv/bin/activate" to activate venv (only needed if not running commands from the run script)'
}

function formatter {
  _source_venv
  # Format Python code with black
  command black .
}

function check_format {
  _source_venv
  # Format Python code with black
  command black . --check
}

function test {
  _source_venv
  python -m unittest discover -s src
}

function linter {
  _source_venv
  command flake8
}

function _create_docker_volume {
  command mkdir -p docker_volume
}

function remove_docker_containers {
  docker-compose ps -q | xargs docker rm
}

function remove_docker_images {
  docker-compose config --images | xargs docker rmi
}

function start {
  _create_docker_volume
  docker-compose up --build "${@}"
}

function start:testing {
  _create_docker_volume
  docker-compose --profile testing up --build "${@}"
}

function stop {
  docker-compose --profile testing stop
}

function help {
  printf "%s <task> \n\nTasks:\n" "${0}"
  compgen -A function | grep -v "^_" | cat -n
}

USER_ID=$(id -u) GROUP_ID=$(id -g) "${@:-help}"
